# vim:ft=kitty

shell fish

font_family family='MonoLisa Nerd Font' style='Black Regular' postscript_name=MonoLisaNF-BlackRegular features="+ss02 +ss11 +liga +calt +ss04 +zero +ss07 +ss12 +ss13 +ss14 +ss15 +ss16 +ss17"
bold_font family='MonoLisa Nerd Font' style='Black Regular' postscript_name=MonoLisaNF-BlackRegular features="+ss02 +ss11 +liga +calt +ss04 +zero +ss07 +ss12 +ss13 +ss14 +ss15 +ss16 +ss17"
italic_font family='MonoLisa Nerd Font' style='Black Italic' postscript_name=MonoLisaNF-BlackItalic features="+ss02 +ss11 +liga +calt +ss04 +zero +ss07 +ss12 +ss13 +ss14 +ss15 +ss16 +ss17"
bold_italic_font family='MonoLisa Nerd Font' style='Black Italic' postscript_name=MonoLisaNF-BlackItalic features="+ss02 +ss11 +liga +calt +ss04 +zero +ss07 +ss12 +ss13 +ss14 +ss15 +ss16 +ss17"
disable_ligatures never

font_size 9.0
cursor_shape block
cursor_trail 1
cursor_trail_decay 0.1 0.4
confirm_os_window_close 0

# The basic colors
foreground              #F6DDDA
background              #1D100F
selection_foreground    #E1BFBB
selection_background    #59413F

# Cursor colors
cursor                  #CCB4AB
cursor_text_color       #1D100F

# URL underline color when hovering with mouse
url_color               #FF544B

# Kitty window border colors
active_border_color     #F6DDDA
inactive_border_color   #A88A87
bell_border_color       #FFDFD2

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

# Tab bar colors
active_tab_foreground   #F6DDDA
active_tab_background   #1D100F
inactive_tab_foreground #F6DDDA
inactive_tab_background #1D100F
tab_bar_background      #FFDAD6

# Colors for marks (marked text in the terminal)
mark1_foreground #76312D
mark1_background #F6DDDA
mark2_foreground #76312D
mark2_background #F6DDDA
mark3_foreground #76312D
mark3_background #F6DDDA

# The 16 terminal colors

# black
color0 #1D100F
color8 #CCB4AB

# red
color1 #FF544B
color9 #FFABA1

# green
color2  #FFBF8C
color10 #FFFBFF

# yellow
color3  #FFDFD2
color11 #FFFFFF

# blue
color4  #B8AC66
color12 #F3D9AB

# magenta
color5  #F08F9B
color13 #FFCED0

# cyan
color6  #F9BF70
color14 #FFF9F5

# white
color7  #EFD3C6
color15 #FFDAD6
