[mgr]
cwd = { fg = "{{colors.primary.default.hex}}", italic = true }

# Hovered
hovered = { bg = "{{colors.primary.default.hex}}", fg = "{{colors.on_primary.default.hex}}" }
preview_hovered = { bold = false }

# Find
find_keyword = { fg = "{{colors.inverse_primary.default.hex}}", reversed = true }
find_position = { fg = "{{colors.surface_container_highest.default.hex}}", bold = true, italic = true }

# Marker
marker_selected = { fg = "{{colors.outline.default.hex}}", bg = "{{colors.outline.default.hex}}" }
marker_copied = { fg = "{{colors.tertiary_container.default.hex}}", bg = "{{colors.tertiary_container.default.hex}}" }
marker_cut = { fg = "{{colors.error_container.default.hex}}", bg = "{{colors.error_container.default.hex}}" }
marker_marked = { fg = "{{colors.outline_variant.default.hex}}", bg = "{{colors.outline_variant.default.hex}}" }

# Count
count_copied = { fg = "{{colors.secondary_container.default.hex}}", bold = true, reversed = true }
count_cut = { fg = "{{colors.error_container.default.hex}}", bold = true, reversed = true }
count_selected = { fg = "{{colors.outline.default.hex}}", bold = true, reversed = true }

# Border
border_symbol = "│"
border_style = { fg = "{{colors.outline.default.hex}}" }

[tabs]
inactive = { fg = "{{colors.on_surface.default.hex}}", bg = "{{colors.surface_container_high.default.hex}}", bold = true }
active = { fg = "{{colors.surface_variant.default.hex}}", bg = "{{colors.secondary.default.hex}}" }
sep_inner = { open = "", close = "" }
sep_outer = { open = "", close = "" }

[mode]
# Normal mode
normal_main = { fg = "{{colors.surface_variant.default.hex}}", bg = "{{colors.secondary.default.hex}}" }
normal_alt = { fg = "{{colors.on_surface.default.hex}}", bg = "{{colors.surface_container_high.default.hex}}", bold = true }

# Select mode
select_main = { fg = "{{colors.surface_variant.default.hex}}", bg = "{{colors.tertiary.default.hex}}" }
select_alt = { fg = "{{colors.on_surface.default.hex}}", bg = "{{colors.surface_container_high.default.hex}}", bold = true }

# Unset mode
unset_main = { fg = "{{colors.surface_variant.default.hex}}", bg = "{{colors.primary.default.hex}}", bold = true }
unset_alt = { fg = "{{colors.primary.default.hex}}", bg = "{{colors.primary.default.hex}}" }

[status]
overall = { fg = "{{colors.on_surface.default.hex}}" }

# Permissions
perm_type = { fg = "{{colors.outline.default.hex}}" }
perm_read = { fg = "{{colors.secondary.default.hex}}" }
perm_write = { fg = "{{colors.tertiary.default.hex}}" }
perm_exec = { fg = "{{colors.primary.default.hex}}" }
perm_sep = { fg = "{{colors.outline.default.hex}}" }

# Progress
progress_label = { fg = "{{colors.background.default.hex}}" }
progress_normal = { fg = "{{colors.secondary.default.hex}}", bg = "{{colors.on_secondary.default.hex}}" }
progress_error = { bg = "{{colors.error_container.default.hex}}" }

[which]
cols = 3
mask = { bg = "{{colors.surface_container_low.default.hex}}" }
cand = { fg = "{{colors.primary.default.hex}}" }
rest = { fg = "{{colors.tertiary.default.hex}}" }
desc = { fg = "{{colors.on_surface.default.hex}}", bold = true }
separator = " "
separator_style = {}

[confirm]
border = { fg = "{{colors.outline.default.hex}}" }
title = { fg = "{{colors.primary.default.hex}}", bold = true }
content = { fg = "{{colors.on_primary.default.hex}}", bold = true }
list = { fg = "{{colors.on_surface.default.hex}}" }
btn_no = { fg = "{{colors.on_surface.default.hex}}", bg = "{{colors.surface_container_high.default.hex}}", bold = true }
btn_yes = { fg = "{{colors.surface_variant.default.hex}}", bg = "{{colors.secondary.default.hex}}" }

[spot]
border = { fg = "{{colors.outline.default.hex}}" }
title = { fg = "{{colors.primary.default.hex}}", bold = true }
tbl_col = { fg = "{{colors.surface_variant.default.hex}}" }
tbl_cell = { bg = "{{colors.primary.default.hex}}" }

[notify]
title_info = { fg = "{{colors.error_container.default.hex}}" }
title_warn = { fg = "{{colors.secondary_container.default.hex}}" }
title_error = { fg = "{{colors.error_container.default.hex}}" }

[pick]
border = { fg = "{{colors.outline.default.hex}}", bold = true }
active = { fg = "{{colors.primary.default.hex}}" }
inactive = { fg = "{{colors.surface_variant.default.hex}}" }

[input]
border = { fg = "{{colors.outline.default.hex}}" }
title = { fg = "{{colors.primary.default.hex}}", bold = true }
value = { fg = "{{colors.on_surface.default.hex}}" }
selected = { bg = "{{colors.primary.default.hex}}" }

[cmp]
border = { fg = "{{colors.outline.default.hex}}", bold = true }
active = { fg = "{{colors.primary.default.hex}}", bg = "{{colors.primary.default.hex}}" }
inactive = { fg = "{{colors.surface_variant.default.hex}}" }

[tasks]
border = { fg = "{{colors.surface_container_high.default.hex}}" }
title = { fg = "{{colors.surface_container_highest.default.hex}}", bold = true }
hovered = { bg = "{{colors.primary.default.hex}}" }

[help]
on = { fg = "{{colors.error_container.default.hex}}" }
run = { fg = "{{colors.primary.default.hex}}" }
desc = { fg = "{{colors.surface_container_highest.default.hex}}", italic = true }
hovered = { bg = "{{colors.primary.default.hex}}" }
footer = { fg = "{{colors.on_surface.default.hex}}", bg = "{{colors.secondary.default.hex}}", bold = true }

[filetype]
rules = [
  # Media
  { mime = "image/*", fg = "{{colors.error_container.default.hex}}" },
  { mime = "video/*", fg = "{{colors.secondary_container.default.hex}}" },
  { mime = "audio/*", fg = "{{colors.tertiary_container.default.hex}}" },

  # Broken symbolic link
  { name = "*", is = "orphan", fg = "{{colors.surface_container_highest.default.hex}}", crossed = true },
  { name = "*/", is = "orphan", fg = "{{colors.surface_container_highest.default.hex}}", crossed = true },

  # Symbolic links
  { name = "*", is = "link", fg = "{{colors.secondary_fixed.default.hex}}" },
  { name = "*/", is = "link", fg = "{{colors.secondary_fixed.default.hex}}" },

  # Executable
  { name = "*", is = "exec", fg = "{{colors.primary.default.hex}}" },

  # Empty files
  { mime = "inode/empty", fg = "{{colors.surface_container_highest.default.hex}}" },

  # Fallback
  { name = "*/", is = "hidden", fg = "{{colors.on_surface.default.hex}}", italic = true },
  { name = "*", is = "hidden", fg = "{{colors.outline.default.hex}}", italic = true },
  { name = "*/", fg = "{{colors.on_surface.default.hex}}" },
  { name = "*", fg = "{{colors.outline.default.hex}}" },
]
