# Don't print a new line at the start of the prompt
add_newline = false
# Pipes ╰─ ╭─
# Powerline symbols                                     
# Wedges 🭧🭒 🭣🭧🭓
# Random noise 🬖🬥🬔🬗
# Cool stuff 󰜥   

format = """
$os$directory$git_branch$git_status$git_metrics
$character
"""

right_format = """$time$cmd_duration"""

[os.symbols]                            # The name of the module we are configuring is "character"
Arch = "󰣇"
[os]                            # The name of the module we are configuring is "character"
disabled = false
format = '[ $symbol ](bg:yellow fg:black)[](fg:yellow)'

# Replace the "❯" symbol in the prompt with "➜"
[character]                            # The name of the module we are configuring is "character"
success_symbol = "[  ](bold fg:blue)" 
error_symbol = "[ ERRO ](bg:red fg:white)[ ](bold fg:red)"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = false

[git_branch]
style = "bg: cyan"
symbol = "󰘬"
truncation_length = 12
truncation_symbol = ""
format = "[](bold fg:cyan)[ $symbol $branch(:$remote_branch)](fg:black bg:cyan)"

[git_metrics]
disabled = false
only_nonzero_diffs = true
added_style = 'bold blue'
format = '[(  $added )(  $deleted )](bg:cyan fg:black)[](fg:cyan)'

[git_status]
conflicted = "  ($count) "
ahead = "  ($count) "
behind = "   ($count) "
diverged = "   ($count) "
untracked = "  ($count) "
stashed = "  ($count) "
modified = "  ($count) "
staged = '  ($count) '
renamed = "  ($count) "
deleted = "  ($count) "
style = "bg: cyan"
format = '[ ($all_status)](bg:cyan fg:black)'

[hostname]
ssh_only = false
format =  "[•$hostname](bg:cyan bold fg:black)[](bold fg:cyan)"
trim_at = ".companyname.com"
disabled = false

[line_break]
disabled = false

[memory_usage]
disabled = true
threshold = -1
symbol = " "
style = "bold dimmed green"

[username]
style_user = "bold bg:cyan fg:black"
style_root = "red bold"
format = "[](bold fg:cyan)[$user]($style)"
disabled = false
show_always = true

[directory]
home_symbol = "~"
read_only = " "
style = "bg:green fg:black"
truncation_length = 6
truncation_symbol = ""
format = '[](bold fg:green)[ 󰉋 $path ]($style)[](bold fg:green)'

[directory.substitutions]
"Documentos" = "󰈔"
"Downloads" = ""

[time]
disabled = false
time_format = "%T"
format = '[](bold fg:yellow)[ $time ](bg:yellow fg:black)'

[cmd_duration]
min_time = 0
format = '[ 󰔛 $duration  ](bg:yellow fg:black)'
