# vim:ft=kitty

shell fish

font_family family='MonoLisa Nerd Font' postscript_name=MonoLisaNF-Regular features='+ss02 +ss11 +liga +calt +ss04 +zero +ss07 +ss12 +ss13 +ss14 +ss15 +ss16 +ss17'
bold_font auto
italic_font auto
bold_italic_font auto
disable_ligatures never

font_size 9.0
cursor_shape block
cursor_trail 1
cursor_trail_decay 0.1 0.4
confirm_os_window_close 0

# The basic colors
foreground              #F6DDDA
background              #1D100F
selection_foreground    #E1BFBB
selection_background    #59413F

# Cursor colors
cursor                  #CCB4AF
cursor_text_color       #1D100F

# URL underline color when hovering with mouse
url_color               #FF554E

# Kitty window border colors
active_border_color     #F6DDDA
inactive_border_color   #A88A87
bell_border_color       #FFDFD7

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

# Tab bar colors
active_tab_foreground   #F6DDDA
active_tab_background   #1D100F
inactive_tab_foreground #F6DDDA
inactive_tab_background #1D100F
tab_bar_background      #FFDAD6

# Colors for marks (marked text in the terminal)
mark1_foreground #76312D
mark1_background #F6DDDA
mark2_foreground #76312D
mark2_background #F6DDDA
mark3_foreground #76312D
mark3_background #F6DDDA

# The 16 terminal colors

# black
color0 #1D100F
color8 #FF554E

# red
color1 #FF554E
color9 #FFABA2

# green
color2  #FFBDA3
color10 #FFFCFF

# yellow
color3  #FFDFD7
color11 #FFFFFF

# blue
color4  #B8AC66
color12 #F9D7AC

# magenta
color5  #F18F91
color13 #FFCECD

# cyan
color6  #FFBA92
color14 #FFF9F7

# white
color7  #F0D1CA
color15 #FFDAD6
