# vim:ft=kitty

shell fish

font_family      family='JetBrainsMono Nerd Font' postscript_name=JetBrainsMonoNF-ExtraBold
bold_font        auto
italic_font      family='JetBrainsMono Nerd Font' postscript_name=JetBrainsMonoNF-BoldItalic
bold_italic_font family='JetBrainsMono Nerd Font' postscript_name=JetBrainsMonoNF-ExtraBoldItalic
font_size 9.0
cursor_shape block
cursor_trail 1
cursor_trail_decay 0.1 0.4
confirm_os_window_close 0

# The basic colors
foreground              #F1DFDC
background              #1A1110
selection_foreground    #D8C2BE
selection_background    #534341

# Cursor colors
cursor                  #CCB4AE
cursor_text_color       #1A1110

# URL underline color when hovering with mouse
url_color               #FF5642

# Kitty window border colors
active_border_color     #F1DFDC
inactive_border_color   #A08C89
bell_border_color       #FFDFD5

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

# Tab bar colors
active_tab_foreground   #F1DFDC
active_tab_background   #1A1110
inactive_tab_foreground #F1DFDC
inactive_tab_background #1A1110
tab_bar_background      #FFDBD5

# Colors for marks (marked text in the terminal)
mark1_foreground #5D3F3A
mark1_background #F1DFDC
mark2_foreground #5D3F3A
mark2_background #F1DFDC
mark3_foreground #5D3F3A
mark3_background #F1DFDC

# The 16 terminal colors

# black
color0 #1A1110
color8 #FF5642

# red
color1 #FF5642
color9 #FFAB9D

# green
color2  #FFBD9F
color10 #FFFBFF

# yellow
color3  #FFDFD5
color11 #FFFFFF

# blue
color4  #B8AC66
color12 #F9D7AC

# magenta
color5  #F1908B
color13 #FFCECA

# cyan
color6  #FFBA8E
color14 #FFF9F8

# white
color7  #F0D3C9
color15 #FFDBD5
