# You can make apps auto-start here
# Relevant Hyprland wiki section: https://wiki.hyprland.org/Configuring/Keywords/#executing

# Cursor
exec-once = hyprctl setcursor Bibata-Modern-Ice 20

# Custom
exec-once = blueman-applet
exec-once = nm-applet --indicator
exec-once = solaar --window=hide
exec-once = clipse -listen   
exec-once = kando
exec-once = fusuma
