# See https://wiki.hyprland.org/Configuring/Binds/
#!
##! Extra keybinds
bind = Ctrl+Super+Alt, Slash, exec, xdg-open ~/.config/hypr/custom/keybinds.conf # Edit extra keybinds

# Add stuff here
# Use #! to add an extra column on the cheatsheet
# Use ##! to add a section in that column
# Add a comment after a bind to add a description, like above

unbind = Super, Super_L, Toggle overview, global, quickshell:overviewToggleRelease # Toggle overview/launcher
unbind = Super, mouse:274 

unbind = Super, I
bind = Super, I, exec, google-chrome-stable

unbind = Super, N
bind = Super, N, exec, kitty -e nvim

unbind = Super, T
bind = Super, T, exec, kitty

unbind = Super, Return
bind = Super, Return, exec, kitty -T footwindow

unbind = ,print
bind = ,print, exec, flameshot gui

unbind = Super, Z
bind = Super, Z, exec, kitty -e nchat

unbind = Super, S
bind = Super, S, exec, kitty -e ncspot

unbind = Super,V
bind = Super, V, exec, kitty --class clipse -e 'clipse'

bind = Super, Escape, exec, sherlock

# Hyprland
unbind = Super, O
bind = Super, O, togglesplit

unbind = Super, W
bind = Super, W, togglefloating

bind = Super, mouse:274, global, kando:main
bind = Super, x, global, kando:main
bind = Super, m, global, kando:workspaces
