# You can put your preferred keybinds here
# https://wiki.hyprland.org/Configuring/Binds/

# Apps
unbind = Super, I
bind = Super, I, exec, vivaldi-stable

unbind = Super, E
bind = Super, E, exec, nemo

unbind = Super, N
bind = Super, N, exec, kitty -e nvim

unbind = Super, T
bind = Super, T, exec, kitty

unbind = Super, Return
bind = Super, Return, exec, kitty -T footwindow

unbind = ,print
bind = ,print, exec, flameshot gui

unbind = Super, Z
bind = Super, Z, exec, kitty -e nchat

unbind = Super, S
bind = Super, S, exec, kitty -e ncspot

unbind = Super,V
bind = Super, V, exec, kitty --app-id clipse -e zsh -c 'cat ~/.cache/ags/user/generated/terminal/sequences.txt & clipse $PPID' 

# Ags
unbind = Super, B
bind = Super, B, exec, ags run-js 'cycleMode();'

bind = ,XF86Presentation,togglespecialworkspace
bind = Super,XF86Presentation,movetoworkspacesilent,special

unbind = Super, Super_L
unbind = Super, escape
bind = Super, escape, exec, ags -t 'overview'

# Hyprland
unbind = Super, O
bind = Super, O, togglesplit

unbind = Super, W
bind = Super, W, togglefloating

bind = Super, mouse:274, global, kando:main
bind = Super, x, global, kando:main
bind = Super, m, global, kando:workspaces
