# You can put custom rules here
# Window/layer rules: https://wiki.hyprland.org/Configuring/Window-Rules/
# Workspace rules: https://wiki.hyprland.org/Configuring/Workspace-Rules/

# Android Studio
windowrulev2 = float,class:^(jetbrains-.*),title:^(Welcome to Android Studio)
windowrulev2 = center,class:^(jetbrains-.*),title:^(Welcome to Android Studio)
windowrulev2 = size 40% 40%,class:^(jetbrains-.*),title:^(Welcome to Android Studio)
windowrulev2 = tile,class:^(jetbrains-.*),title:^(Running Devices -.*)
windowrulev2 = tile,class:^(jetbrains-.*),title:^(Logcat -.*)
windowrulev2 = noborder, class:^(jetbrains-.*)(.*)$
windowrulev2 = noinitialfocus,class:^(jetbrains-.*),title:^(win.*)
windowrulev2 = noborder, class:^(jetbrains-.*),title:^(win.*)
windowrulev2 = rounding 0, class:^(jetbrains-.*),title:^(win.*)

# Clipse
windowrulev2 = float,class:(clipse) 
windowrulev2 = center,class:(clipse) 
windowrulev2 = size 27% 60%,class:(clipse) 
windowrulev2 = animation slide bottom,class:(clipse) 
windowrulev2 = dimaround,class:(clipse) 

# EOG
windowrulev2 = float,class:(eog)
windowrulev2 = center,class:(eog)
windowrulev2 = size 27% 60%,class:(eog) 

# kando
windowrule = noblur, class:kando 
windowrule = noborder, class:kando
windowrule = noanim, class:kando
windowrule = float, class:kando
windowrule = pin, class:kando
windowrule = size 100% 100%, class:kando

# File-roller
windowrulev2 = float,class:(org.gnome.FileRoller)
windowrule = size 40% 40%, class:(org.gnome.FileRoller)

# Foot
windowrulev2 = float,title:(^footwindow)
windowrulev2 = size 40% 40%, title:(^footwindow)
windowrulev2 = center,title:(^footwindow)
