# You can put custom rules here
# Window/layer rules: https://wiki.hyprland.org/Configuring/Window-Rules/
# Workspace rules: https://wiki.hyprland.org/Configuring/Workspace-Rules/

# Vivaldi
windowrule = tile, (Vivaldi-stable)
windowrule = float, title:^(Salvar arquivo)$
windowrule = float, title:^(Bitwarden - Vivaldi)$
windowrulev2 = float, title:^(Abrir arquivo)$

# Rofi
windowrulev2=dimaround,title:^(rofi)
windowrulev2=center,title:^(rofi)

# Yad
windowrulev2 = float, class:^(yad)$
windowrulev2 = float, class:^(file-roller)$

# Android Studio
windowrule = float, title:^(Welcome to Android Studio)$
windowrulev2 = noborder, class:^(jetbrains-.*)(.*)$
windowrulev2 = noinitialfocus,class:^(jetbrains-.*),title:^(win.*)
windowrulev2 = noborder, class:^(jetbrains-.*),title:^(win.*)
windowrulev2 = rounding 0, class:^(jetbrains-.*),title:^(win.*)

# Clipse
windowrulev2 = float,class:(clipse) 
windowrulev2 = center,class:(clipse) 
windowrulev2 = size 27% 60%,class:(clipse) 
windowrulev2 = animation slide bottom,class:(clipse) 
windowrulev2 = dimaround,class:(clipse) 

# Nemo
windowrulev2 = float,title:^(Propriedades de),class:(nemo)

# EOG
windowrulev2 = float,class:(eog)
windowrulev2 = center,class:(eog)
windowrulev2 = size 27% 60%,class:(eog) 

# kand90o
windowrule = noblur, kando 
windowrule = noborder, kando90
windowrule = noanim, kando
windowrule = float, kando
windowrule = pin, kando
windowrule = size 100% 100%, kando

# File-roller
windowrulev2 = float,class:(org.gnome.FileRoller)
windowrule = size 40% 40%, org.gnome.FileRoller

# Foot
windowrulev2 = float,title:(^footwindow)
windowrule = size 40% 40%, title:(^footwindow)
windowrulev2 = center,title:(^footwindow)
