# exec = export SLURP_ARGS='-d -c D5E4F6BB -b 3A485744 -s 00000000'

general {
    col.active_border = rgba(E0E2E839)
    col.inactive_border = rgba(8C919830)
}

misc {
    background_color = rgba(101418FF)
}

windowrulev2 = bordercolor rgba(9ACBFAAA) rgba(9ACBFA77),pinned:1
