# exec = export SLURP_ARGS='-d -c ABF0DEBB -b 01564844 -s 00000000'

general {
    col.active_border = rgba(00E29Cff)
    col.inactive_border = rgba(07160F00)
}

misc {
    background_color = rgba(07160FFF)
}

plugin {
    hyprbars {
        # Honestly idk if it works like css, but well, why not
        bar_text_font = Rubik, Geist, AR One Sans, Reddit Sans, Inter, Roboto, Ubuntu, Noto Sans, sans-serif
        bar_height = 30
        bar_padding = 10
        bar_button_padding = 5
        bar_precedence_over_border = true
        bar_part_of_window = true

        bar_color = rgba(07160FFF)
        col.text = rgba(D4E7DAFF)


        # example buttons (R -> L)
        # hyprbars-button = color, size, on-click
        hyprbars-button = rgb(D4E7DA), 13, 󰖭, hyprctl dispatch killactive
        hyprbars-button = rgb(D4E7DA), 13, 󰖯, hyprctl dispatch fullscreen 1
        hyprbars-button = rgb(D4E7DA), 13, 󰖰, hyprctl dispatch movetoworkspacesilent special
    }
}

windowrulev2 = bordercolor rgba(00E29CAA) rgba(00E29C77),pinned:1
