# exec = export SLURP_ARGS='-d -c FFDCC6BB -b 6D3D1844 -s 00000000'

general {
    col.active_border = rgba(FFB59Fff)
    col.inactive_border = rgba(200F0900)
}

misc {
    background_color = rgba(200F09FF)
}

plugin {
    hyprbars {
        # Honestly idk if it works like css, but well, why not
        bar_text_font = Rubik, Geist, AR One Sans, Reddit Sans, Inter, Roboto, Ubuntu, Noto Sans, sans-serif
        bar_height = 30
        bar_padding = 10
        bar_button_padding = 5
        bar_precedence_over_border = true
        bar_part_of_window = true

        bar_color = rgba(200F09FF)
        col.text = rgba(FFDBD1FF)


        # example buttons (R -> L)
        # hyprbars-button = color, size, on-click
        hyprbars-button = rgb(FFDBD1), 13, 󰖭, hyprctl dispatch killactive
        hyprbars-button = rgb(FFDBD1), 13, 󰖯, hyprctl dispatch fullscreen 1
        hyprbars-button = rgb(FFDBD1), 13, 󰖰, hyprctl dispatch movetoworkspacesilent special
    }
}

windowrulev2 = bordercolor rgba(FFB59FAA) rgba(FFB59F77),pinned:1
