general {
    col.active_border = rgb(FFB3AD)
    col.inactive_border = rgb(1D100F)
}

misc {
    background_color = rgb(1D100F)
}

group {
    col.border_active = rgb(FFB3AD)
    col.border_inactive = rgb(1D100F)
    col.border_locked_active = rgb(F4BC7D)
    col.border_locked_inactive = rgb(1D100F)
    groupbar {
      col.active = rgb(FFB3AD)
      col.inactive = rgb(2A1C1B)
      col.locked_active = rgb(F4BC7D)
      col.locked_inactive = rgb(1D100F)
      text_color = rgb(2A1C1B)
      text_color_inactive = rgb(FFB3AD)
    }
}

plugin {
    hyprbars {
        # Honestly idk if it works like css, but well, why not
        bar_text_font = Rubik, Geist, AR One Sans, Reddit Sans, Inter, Roboto, Ubuntu, Noto Sans, sans-serif
        bar_height = 30
        bar_padding = 10
        bar_button_padding = 5
        bar_precedence_over_border = true
        bar_part_of_window = true

        bar_color = rgb(680009)
        col.text = rgb(FFB3AD)


        # example buttons (R -> L)
        # hyprbars-button = color, size, on-click
        hyprbars-button = rgb(#primary #), 13, 󰖭, hyprctl dispatch killactive
        hyprbars-button = rgb(#primary #), 13, 󰖯, hyprctl dispatch fullscreen 1
        hyprbars-button = rgb(#primary #), 13, 󰖰, hyprctl dispatch movetoworkspacesilent special
    }
}

windowrulev2 = bordercolor rgba(FFB3AD) rgba(1D100F),pinned:1
