[[mgr.prepend_keymap]]
on = "<Space>"
run = "plugin bunny"
desc = "Start bunny.yazi"

[[mgr.prepend_keymap]]
on = "'"
run = "plugin bunny fuzzy"
desc = "Start bunny.yazi fuzzy search"

[[mgr.prepend_keymap]]
on = "O"
run = 'tab_create ~/'
desc = "New Tab"

[[mgr.prepend_keymap]]
on = "o"
run = 'tab_create --current'
desc = "New Tab"

[[mgr.prepend_keymap]]
on = "<A-Enter>"
run = 'open --interactive'
desc = "Open interactive"

[[mgr.prepend_keymap]]
on = "<C-Enter>"
run = 'shell "kitty -e nvim $0" --orphan'
desc = "Open in other shell"

[[mgr.prepend_keymap]]
on = "<Enter>"
run = 'open'
desc = "Open"

[[mgr.prepend_keymap]]
on = "t"
run = 'shell "$SHELL" --block'
desc = "Open $SHELL here"

[[mgr.prepend_keymap]]
on = "T"
run = 'shell --interactive'
desc = "Open $SHELL here"

[[mgr.prepend_keymap]]
on = "y"
run = [
  'shell -- for path in "$@"; do echo "file://$path"; done | wl-copy -t text/uri-list',
  "yank",
]

[[mgr.prepend_keymap]]
on = "<Tab>"
run = "toggle"
desc = "Toggle selection"

[[mgr.prepend_keymap]]
on = "i"
run = "spot"
desc = "File info"

[[mgr.prepend_keymap]]
on = "m"
run = "yank --cut"
desc = "Cut"

[[mgr.prepend_keymap]]
on = "<Esc>"
run = "unyank"
desc = "Cancel yank status"

[[mgr.prepend_keymap]]
on = "x"
run = "yank --cut"
desc = "Cut"

[[mgr.prepend_keymap]]
on = "q"
run = "close"
desc = "Close Tab"

[[mgr.prepend_keymap]]
on = "<A-1>"
run = "tab_switch 0"
desc = "To Tab 1"

[[mgr.prepend_keymap]]
on = "<A-2>"
run = "tab_switch 1"
desc = "To Tab 2"

[[mgr.prepend_keymap]]
on = "<A-3>"
run = "tab_switch 2"
desc = "To Tab 3"

[[mgr.prepend_keymap]]
on = "<A-4>"
run = "tab_switch 3"
desc = "To Tab 4"

[[mgr.prepend_keymap]]
on = "<A-5>"
run = "tab_switch 4"
desc = "To Tab 5"

[[mgr.prepend_keymap]]
on = "<A-6>"
run = "tab_switch 5"
desc = "To Tab 6"

[[mgr.prepend_keymap]]
on = "<A-7>"
run = "tab_switch 6"
desc = "To Tab 7"

[[mgr.prepend_keymap]]
on = "<A-8>"
run = "tab_switch 7"
desc = "To Tab 8"

[[mgr.prepend_keymap]]
on = "<A-9>"
run = "tab_switch 8"
desc = "To Tab 9"

[[mgr.prepend_keymap]]
on = "<A-0>"
run = "tab_switch 9"
desc = "To Tab 10"

[[mgr.prepend_keymap]]
on = "K"
run = "tab_switch 1 --relative"
desc = "Next Tab"

[[mgr.prepend_keymap]]
on = "J"
run = "tab_switch -1 --relative"
desc = "Previous Tab"
