[[plugin.prepend_fetchers]]
id = "git"
name = "*"
run = "git"

[[plugin.prepend_fetchers]]
id = "git"
name = "*/"
run = "git"

[mgr]
ratio = [1, 1, 2]
sort_by = "natural"
sort_dir_first = true
show_hidden = true

[opener]
edit = [{ run = 'nvim "$@"', block = true, for = "unix" }]
open = [{ run = 'xdg-open "$@"', desc = "Open" }]
play = [{ run = 'vlc "$@"', orphan = true, for = "unix" }]
