general {
    col.active_border = rgb($primary #)
    col.inactive_border = rgb($background #)
}

misc {
    background_color = rgb($background #)
}

group {
    col.border_active = rgb($primary #)
    col.border_inactive = rgb($background #)
    col.border_locked_active = rgb($tertiary #)
    col.border_locked_inactive = rgb($background #)
    groupbar {
      col.active = rgb($primary #)
      col.inactive = rgb($surfaceContainer #)
      col.locked_active = rgb($tertiary #)
      col.locked_inactive = rgb($background #)
      text_color = rgb($surfaceContainer #)
      text_color_inactive = rgb($primary #)
    }
}

plugin {
    hyprbars {
        # Honestly idk if it works like css, but well, why not
        bar_text_font = Rubik, Geist, AR One Sans, Reddit Sans, Inter, Roboto, Ubuntu, Noto Sans, sans-serif
        bar_height = 30
        bar_padding = 10
        bar_button_padding = 5
        bar_precedence_over_border = true
        bar_part_of_window = true

        bar_color = rgb($onPrimary #)
        col.text = rgb($primary #)


        # example buttons (R -> L)
        # hyprbars-button = color, size, on-click
        hyprbars-button = rgb(#primary #), 13, 󰖭, hyprctl dispatch killactive
        hyprbars-button = rgb(#primary #), 13, 󰖯, hyprctl dispatch fullscreen 1
        hyprbars-button = rgb(#primary #), 13, 󰖰, hyprctl dispatch movetoworkspacesilent special
    }
}

windowrulev2 = bordercolor rgba($primary #) rgba($background #),pinned:1
